### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Piaotian** [AMP-SCZ/coding-test#1]
Hi Tashrif,

Thank you for setting this up. I have some questions about the tasks.

1. To anonymize the date of consent, does it mean for each record, generate a random date between 1/1/1 and 12/31/1924, then calculate the offset between random date and date of consent, and finally save the offset data to a new csv?

2. For the second task in Anonymize, the final csv will includes columns: site ID, the original date of consent, cohort, age. 

3. Finally, I will push 2 csv back, enroll_data_offset_{your_initials}.csv and enroll_data_anon_{your_initials}.csv

4. For the Task 2, can I use libraries to draw the chart?

Please let me know if I misunderstood anything. Thank you very much!

Best,
Piaotian

**Comment by tashrifbillah** [comment]
1. Random date between first and last date of 1924 will be fine, yes, yes
2. Refer to our instruction:

> Modify the csv by replacing given dates to ones earlier than year 1925

Final csv file will include columns: site ID, disguised date of consent, cohort, age

3. Yes

4. Any and all JavaScript libraries

cc @sbouix
