### ISSUE TITLE
Clarification with the integer atlas labels

### ISSUE THREAD

**Issue by shrikanth95** [AMP-SCZ/coding-test#2]
I was looking at the input volumes (using freeview) and realized that the atlas label volume (atlas-integer-label.nii.gz) was different from what I expected. 

- Specifically, as the atlas is a MNI 1mm T1 contrast volume, I was expecting the label volume to also be a volume of size 182x218x182. However, the size of atlas-integer-label.nii.gz is 182x218x182x9. (found this using the mri_info command)
- Further, it looks like the atlas labels do not overlap with atlas volume (see screenshots below). 
    1. Screenshot 1: Shows the atlas labels overlayed on top of the T1 image. Seems like all the labels are restricted towards the center. 
    2. Screenshot 2: Shows only the voxels corresponding to the brain-stem (voxel label 16). 

I wanted to double check if this was as expected - please let me know if I am missing something. Thank you.

## Screenshot 1: 
![image](https://user-images.githubusercontent.com/19792746/190870671-30417ebe-f745-449d-9fc9-98933d4ee764.png)

## Screenshot 2:
![image](https://user-images.githubusercontent.com/19792746/190871220-c66092f5-067e-4cf8-a6e3-01d4489cfd61.png)

**Comment by tashrifbillah** [comment]
> Further, it looks like the atlas labels do not overlap with atlas volume

They do not, which is why you need workflow step #1. Please re-read workflow step #2.

**Comment by tashrifbillah** [comment]
> I was expecting the label volume to also be a volume of size 182x218x182

You are right. We made a mistake. Now we have uploaded a proper atlas. Please re-download and use that.
