### ISSUE TITLE
Clarification in Task 2, Workflow 2: Volume calculation

### ISSUE THREAD

**Issue by shrikanth95** [AMP-SCZ/coding-test#3]
I have a quick clarification regarding the procedure to calculate subcortical ROI volumes (Task 2, Workflow 2). The prompt mentions 

_... Multiply the registered image with the binary image. Count the number of 1's in the resultant image. …_

However, the registered image holds a float value between 0 and 380. Multiplying this volume with a binary image will result in another volume with float values. As it does not make sense to "Count the number of 1s" in a volume with float elements. I wanted to double check if I should be performing a logical AND operation between the registered image and the binary image. Thanks!

**Comment by tashrifbillah** [comment]
Would it help if we say "count the number of non-zeros"?

**Comment by shrikanth95** [comment]
Thanks - that works.
