### ISSUE TITLE
conda install -c aramislab ants fails with "RemoveError" for setup tools

### ISSUE THREAD

**Issue by lilytaoyy** [AMP-SCZ/coding-test#4]
Hi,

I was trying to install the ANTs package 2.3.1 (osx-64) in terminal, but it kept failing with 
`RemoveError: 'setuptools' is a dependency of conda and cannot be removed from conda's operating environment.`

It seems like conda was trying to remove the setuptools package during the installation but the process itself would depend on the package?

I have tried some common solutions suggested online:

1. `pip uninstall setuptools` then `conda install setuptools`
2. `conda install -c anaconda setuptools`
3. using `--force` command
4. `conda update setuptools`

Nothing seems to work in my situation. I will continue to try other methods later today, please let me know if you have any good idea to workaround the issue. Thank you!

**Comment by tashrifbillah** [comment]
You have not followed `Prerequisite` section of our instruction. If you do, we can try to help with issues.

**Comment by lilytaoyy** [comment]
> You have not followed `Prerequisite` section of our instruction. If you do, we can try to help with issues.

I tried downloading from `pnlbwh` channel first using the command `conda install -c pnlbwh ants`, but it gave me an environment error
```
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ants
```

**Comment by tashrifbillah** [comment]
Okay I realize that you are using a different OS: `ANTs package 2.3.1 (osx-64)`. Sorry but our package is made for Linux only. I cannot guarantee if it would work in OSX. Instead, you may try `antspy` package:
https://github.com/ANTsX/ANTsPy#installation

ANTs provide pre-built packages too:
https://github.com/ANTsX/ANTs/releases

If all else fails, you can try to build ANTs from source:
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

**Comment by lilytaoyy** [comment]
Thanks, I will try these out!

**Comment by lilytaoyy** [comment]
Sorry to bother you again, I have been trying with different methods this afternoon and evening, but it kept failing with different error messages.

My workflow was very similar to these posts https://github.com/ANTsX/ANTsPy/issues/274 and https://github.com/ANTsX/ANTsPy/issues/381, and got the same issues. 

I have also tried to log onto the virtual machine in Linux at Brown, but unfortunately my access expired due to graduation. So I am a bit confused on what step to take next.

**Comment by tashrifbillah** [comment]
ANTs issues can be solved by ANTs people by opening issues there, not here. We offer you two more days to complete the assignment. Would you like to accept it?

**Comment by lilytaoyy** [comment]
Thanks, I will take the two extra days to see if I can find a solution to the issue.
